layout_spectrum: 0.3975676
typography_spectrum: 0.8635548
color:
  saturation: 0.5135496
  lightness: 0.6249006
  brandStrength: 0.6526092
  rhythmicContrast: 0.8529256
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Ambidiestros
